# Generated by Django 4.1.4 on 2022-12-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('2010', '2010'), ('2015', '2015'), ('2020', '2020')], max_length=20),
        ),
    ]
